version: '3'
services:
  node_server:
    build:
      context: .
    container_name: node_server
    restart: always
    command: sh run-prod.sh
    #networks:
    #  - app-network
    ports:
      - "80:8000"
      - "8000:8000"

# Not in use, as
#    ports:
#     - "80:8000"
#
#  nginx:
#    build:
#        context: ./nginx
#    container_name: nginx
#    depends_on:
#        - "node_server"
#    networks:
#      - app-network
#    ports:
#        - "80:80"
#
#networks:
#  app-network:
#    driver: bridge