version: "3.8"
services:
  react_client:
    container_name: react_client
    build:
      context: ./frontend
  node_server:
    container_name: node_server
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - ./backend/node_modules
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
