-version: "3.8"
services:
  reactClient:
    build:
      context: ./frontend
  nodeServer:
    build:
      context: ./backend
    ports:
      - "8000:8000"
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
